### ISSUE TITLE
`__version__` string in module does not match setup.py version.

### ISSUE THREAD

**Issue by TheElementalOfDestruction** [seamustuohy/RTFDE#12]
The `__version__` string in the module has it listed as `0.00.1` when the setup.py version is 0.0.2 which could interfere with in-code checks for the module version. Additionally, it can lead to general confusion.

I know you have more important things to worry about, so not really too worried about this, but just thought it should be noted.

**Comment by seamustuohy** [comment]
Thanks! I'll make sure to fix this in the next release since a version increase will be coming soon with the other fixes.

**Comment by seamustuohy** [comment]
Addressed in the 0.1.0 version which is in the final notification and testing stage on [dev](https://github.com/seamustuohy/RTFDE/commit/1b29704a47e6c3a118ebb3ed2ac96e640312f8fb)
