### ISSUE TITLE
License clarification needed

### ISSUE THREAD

**Issue by penguinpee** [seamustuohy/RTFDE#24]
The license referenced in the `LICENSE` file is for LGPL-3.0-only (LGPLv3). However the preambles in the python files in `RTFDE/` as well as files in `docs/RTFDE/` and `scripts/` state the applicable license as GPL-3.0-or-later.

It appears the latter is the effective license. If so, could the `LICENSE` file as well as `setup.py` be updated to reflect the actual license that applies to the code?

I can supply a PR to that extent once it is clear which license applies to the code. The issue came to light during package review. I would like to package `RTFDE` for Fedora.

**Comment by penguinpee** [comment]
It looks like the `LICENSE` file was GPL-3.0-only earlier. This was changed in:

2ffdd05afa9a630ea8c79935c992e22443469bc7

Was that intentional?

**Comment by seamustuohy** [comment]
Thank you for catching that. It looks like my snippet for inserting the license language in the code reverted to a backup. The correct License is GNU Lesser General Public License v3.0 (LGPLv3). I'll update all the individual files. 

Best,
s2e

**Comment by penguinpee** [comment]
Thanks. I will apply the patch when it's ready. But maybe this warrants a new release on PyPI? Either way, thank you for clarifying.

**Comment by seamustuohy** [comment]
Addressed by [PR#27](https://github.com/seamustuohy/RTFDE/pull/27). Will be in 0.1.1 release.

**Comment by penguinpee** [comment]
Thanks for fixing that. :+1: 

Are you planning on releasing **0.1.1** soon? If so, I wait. Otherwise, I'll grab the patch.

**Comment by seamustuohy** [comment]
Yup, looking to release before the end of the weekend. I just have to run tests over my corpus of test emails with all the changes in place to make sure I didn't break anything.
