### ISSUE TITLE
'bytes' object does not have attribute "removPrefix"

### ISSUE THREAD

**Issue by AIDBEmon** [seamustuohy/RTFDE#25]
Version of RTFDE==0.1.0

I am using extract_msg library that uses RTFDE library and when I pass a set of msg files, it gives out this error.
This is very rare and hasn't happened quite often. 

![Uploading image.png…]()

Is this a bug? or something to do with the msg itself?

Is there anyway to escape this error?

**Comment by TheElementalOfDestruction** [comment]
Looks like the traceback didn't upload properly so here is a copy.

![image](https://github.com/seamustuohy/RTFDE/assets/24580325/b4e46427-07dd-4701-806a-5b2b396010a9)

Looking at it, I would guess the function is intended for bytes, but I've double checked and the function was added to the bytes class in version 3.9, and so doesn't exist in version 3.8.

**Comment by AIDBEmon** [comment]
Thank you so much @TheElementalOfDestruction. The error is not there for python version 3.9+. I had to upgrade python version to resolve this

**Comment by seamustuohy** [comment]
Will be addressed by PR #28 . This will also move the python version to 3.8. Waiting for the next major change when there is greater adoption of python 3.9 to move library to 3.9 and add removeprefix back in.

**Comment by seamustuohy** [comment]
Addressed in [Release 0.1.1](https://github.com/seamustuohy/RTFDE/releases/tag/0.1.1)

**Comment by AIDBEmon** [comment]
Thank you!
