### ISSUE TITLE
Support for lark >= 1.1.8

### ISSUE THREAD

**Issue by fabaff** [seamustuohy/RTFDE#31]
`lark 1.1.9` was [released](https://github.com/lark-parser/lark/releases/tag/1.1.9) a while back. Currently there is a pin for `lark`.

https://github.com/seamustuohy/RTFDE/blob/5dda668bc11ffa904f414b4b6693972d0a4f0345/setup.py#L29

This is an issue for distributions which are shipping `rtfde` as a lot of them already have `lark 1.1.9`. Do you have any plan to allow `lark >= 1.1.8`.

The pin doesn't affect people who are using a `venv`.

**Comment by seamustuohy** [comment]
@fabaff, during early development I noticed that lark had been quite willing to be innovative in ways that broke things for my RTFDE. That said, I think that a nice compromise between my attempts to have no suprises in my releases and lark's active development would be to track against compatible releases. As such, I've released a minor version update `0.1.2` which tracks against the 1.* releases of lark. I imagine this will require another round of compatibility testing against the 2.0 version in the near future. But, from that point forward should create a nice much longer period before the next time we have this type of issue.
